server:
  port: 80
spring:
  application:
    name: mcroservice-order #服务名

#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
